{{ include('header.phtml') }}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="page-header">
				<h1>Eventos</h1>
			</div>

			<div class="stream-eventos">
				<ul class="list-group">
					{% for evento in eventos %}
						<li class="list-group-item">
							<h2>{{ evento.name }}</h2>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>



{{ include('footer.phtml') }}
