<footer class="page-footer grey darken-4">
	<div class="footer-copyright">
		<div class="container">
			2017 Copyleft - IFSP Boituva
		</div>
	</div>
</footer>

<script src="{{ base_url() }}/assets/node_modules/jquery/dist/jquery.min.js"></script>
<script src="{{ base_url() }}/assets/node_modules/jquery-mask-plugin/dist/jquery.mask.min.js"></script>
<script src="{{ base_url() }}/assets/node_modules/materialize-css/dist/js/materialize.min.js"></script>
<script src="{{ base_url() }}/assets/js/index.js"></script>
<script>

</script>
</body>
</html>