
<script type="text/javascript" src="{{ base_url() }}/assets/bower_components/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="{{ base_url() }}/assets/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{{ base_url() }}/assets/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript" src="{{ base_url() }}/assets/js/index.js"></script>
</body>
</html>