<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>Interdisciplinar</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css" href="{{ base_url() }}/assets/node_modules/materialize-css/dist/css/materialize.min.css">
	<link rel="stylesheet" href="{{ base_url() }}/assets/css/style.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
	<div class="nav-wrapper green darken-1">
		<a href="#" data-activates="slide-out" class="button-collapse right"><i class="material-icons">menu</i></a>
	</div>
</nav>