<div class="collapse navbar-collapse" id="menu">
	<ul class="nav navbar-nav">
		<li class="active"><a href="{{ path_for('eventos') }}"> <i class="glyphicon glyphicon-calendar"></i> Eventos <span class="sr-only">(current)</span></a></li>

		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="glyphicon glyphicon-user"></i> Minha conta <span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><a href="#"> Meus dados</a></li>
				<li role="separator" class="divider"></li>
				<li><a href="#">Comprovante</a></li>
				<li><a href="#">Presenças</a></li>
				<li><a href="#">Certificados</a></li>
			</ul>
		</li>
	</ul>
</div>