	<div class="container login">
		<ul id="slide-out" class="side-nav">
			<li><a href="{{ path_for('eventos') }}">Eventos</a></li>
			<li><div class="divider"></div></li>
			<li><a href="#!">Atualizar Dados Pessoais</a></li>
			<li><div class="divider"></div></li>
			<li><a href="#!">Gerar Comprovante de Inscrição</a></li>
			<li><div class="divider"></div></li>
			<li><a href="#!">Gerar Lista de Presença</a></li>
			<li><div class="divider"></div></li>
			<li><a href="#!">Gerar Certificados</a></li>
			<li><div class="divider"></div></li>
			<li><a href="#!">Sair</a></li>
			<li><div class="divider"></div></li>
		</ul>
	</div>
</main>