{{ include('header.phtml') }}

<div class="container-fluid global-wrapper-login">
	<div class="row">
		<div class="col-md-12 col-xs-12">
			<div class="page-header">
				<h1>Faça login</h1>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="signup-login-form">
			<form action="{{ path_for('auth.login.post') }}" method="POST">
			<div class="col-md-12 col-xs-12">
				<label for="login">CPF:</label>
				<input name="login" class="form-control" required="true" placeholder="">

				<label for="password">Senha:</label>
				<input type="password" name="password" class="form-control" required="true" placeholder="">

				<input type="submit" class="btn btn-primary form-control" name="submit" value="Entrar">
			</div>
			</form>
		</div>
	</div>
</div>

{{ include('footer.phtml') }}
